const COUNTRY_NAMES: Record<string, string> = {
  AB: 'Aruba',
  AG: 'Angola',
  AL: 'Albania',
  AN: 'Andorra',
  AR: 'Argentina',
  AT: 'Antigua and Barbuda',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BD: 'Burundi',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahamas',
  BI: 'Bosnia and Herzegovina',
  BL: 'Belarus',
  BM: 'Bermuda',
  BO: 'Bolivia',
  BR: 'Brazil',
  BW: 'Botswana',
  CA: 'Canada',
  CH: 'Chile',
  CHN: 'China',
  CI: "Côte d'Ivoire",
  CM: 'Cameroon',
  CO: 'Colombia',
  CP: 'Cape Verde',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CY: 'Cyprus',
  CYP: 'Cyprus',
  CZ: 'Czechia',
  CZE: 'Czechia',
  DE: 'Germany',
  DM: 'Dominica',
  DN: 'Denmark',
  DO: 'Dominican Republic',
  DPRK: 'North Korea',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EG: 'Egypt',
  EGY: 'Egypt',
  ES: 'Spain',
  ET: 'Ethiopia',
  ETH: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FR: 'France',
  GB: 'United Kingdom',
  GE: 'Georgia',
  GH: 'Ghana',
  GI: 'Guinea',
  GL: 'Guadeloupe',
  GR: 'Greece',
  GRC: 'Greece',
  GT: 'Guatemala',
  GU: 'Guam',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IM: 'Isle of Man',
  IN: 'India',
  IND: 'India',
  IR: 'Ireland',
  IS: 'Israel',
  ISR: 'Israel',
  IT: 'Italy',
  JA: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  JPN: 'Japan',
  KA: 'Kazakhstan',
  KAZ: 'Kazakhstan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KGZ: 'Kyrgyzstan',
  KN: 'Saint Kitts and Nevis',
  KO: 'Kosovo',
  LB: 'Lebanon',
  LBN: 'Lebanon',
  LC: 'Saint Lucia',
  LK: 'Sri Lanka',
  LKA: 'Sri Lanka',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Madagascar',
  ME: 'Mexico',
  MK: 'North Macedonia',
  ML: 'Malta',
  MN: 'Montenegro',
  MNE: 'Montenegro',
  MO: 'Mozambique',
  MT: 'Martinique',
  MU: 'Mauritius',
  MW: 'Malawi',
  MY: 'Malaysia',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Pakistan',
  PE: 'Peru',
  PH: 'Philippines',
  PO: 'Poland',
  POL: 'Poland',
  PR: 'Portugal',
  PS: 'Palestine',
  PSE: 'Palestine',
  PY: 'French Polynesia',
  QA: 'Qatar',
  RE: 'Réunion',
  RO: 'Romania',
  RU: 'Russia',
  RUS: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SAU: 'Saudi Arabia',
  SD: 'Sudan',
  SDN: 'Sudan',
  SE: 'Senegal',
  SG: 'Singapore',
  SL: 'El Salvador',
  SR: 'Serbia',
  SRB: 'Serbia',
  SU: 'Suriname',
  SV: 'Slovenia',
  SW: 'Sweden',
  SX: 'Sint Maarten',
  SY: 'Syria',
  SYR: 'Syria',
  TG: 'Togo',
  TH: 'Thailand',
  THA: 'Thailand',
  TJ: 'Tajikistan',
  TJK: 'Tajikistan',
  TT: 'Trinidad and Tobago',
  TU: 'Turkey',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UG: 'Uganda',
  UK: 'Ukraine',
  UKR: 'Ukraine',
  UR: 'Uruguay',
  US: 'United States',
  UZ: 'Uzbekistan',
  UZB: 'Uzbekistan',
  VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuela',
  VG: 'British Virgin Islands',
  VI: 'US Virgin Islands',
  VN: 'Vietnam',
  YE: 'Yemen',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

export function countryName(code: string): string {
  return COUNTRY_NAMES[code] || code;
}
